/**
 * editor-images.service.ts
 *
 * Validates editor-image uploads, stores them privately, and resolves
 * tamper-proof render tokens without exposing raw S3 objects publicly.
 */
import {
  BadRequestException,
  Injectable,
  PayloadTooLargeException,
  UnsupportedMediaTypeException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as crypto from 'node:crypto';
import { S3Service } from '../../common/s3/s3.service';

const DEFAULT_MAX_IMAGE_BYTES = 8 * 1024 * 1024;
const DEFAULT_IMAGE_TOKEN_TTL_SECONDS = 30 * 24 * 60 * 60;
const EDITOR_IMAGE_PREFIX = 'document-editor-images';
const TOKEN_VERSION = 'v1';
const ALLOWED_IMAGE_TYPES = new Map<string, string>([
  ['image/avif', 'avif'],
  ['image/gif', 'gif'],
  ['image/jpeg', 'jpg'],
  ['image/png', 'png'],
  ['image/webp', 'webp'],
]);

export interface UploadedEditorImage {
  url: string;
  key: string;
  bytes: number;
  mimeType: string;
}

export interface EditorImageObject {
  buffer: Buffer;
  contentType: string;
  key: string;
  cacheMaxAgeSeconds: number;
}

@Injectable()
export class EditorImagesService {
  private readonly maxImageBytes: number;
  private readonly tokenTtlSeconds: number;

  constructor(
    private readonly config: ConfigService,
    private readonly s3: S3Service,
  ) {
    this.maxImageBytes =
      this.config.get<number>('EDITOR_IMAGE_MAX_SIZE_BYTES') ??
      DEFAULT_MAX_IMAGE_BYTES;
    this.tokenTtlSeconds =
      this.config.get<number>('EDITOR_IMAGE_TOKEN_TTL_SECONDS') ??
      DEFAULT_IMAGE_TOKEN_TTL_SECONDS;
  }

  /**
   * Uploads a validated editor image to private S3 storage and returns a stable
   * signed render URL that can be stored safely in document content.
   *
   * @param userId - Authenticated uploader ID.
   * @param file - Multer in-memory image file.
   * @param apiBaseUrl - Public base URL for this documents API.
   * @returns Stable render URL and upload metadata.
   */
  async upload(
    userId: string,
    file: Express.Multer.File | undefined,
    apiBaseUrl: string,
  ): Promise<UploadedEditorImage> {
    if (!file) {
      throw new BadRequestException('Upload an image file.');
    }

    const extension = this.validateFile(file);
    const key = this.buildObjectKey(userId, extension);

    await this.s3.putBuffer(key, file.buffer, file.mimetype);

    return {
      url: `${apiBaseUrl}/editor-images/render/${this.createImageToken(key)}`,
      key,
      bytes: file.size,
      mimeType: file.mimetype,
    };
  }

  /**
   * Resolves a signed editor-image token and returns the private S3 object.
   *
   * @param token - Opaque signed token generated by upload().
   * @returns Binary image object and content type.
   */
  async getImageByToken(token: string): Promise<EditorImageObject> {
    const resolvedToken = this.verifyImageToken(token);
    const buffer = await this.s3.getBuffer(resolvedToken.key);
    const contentType = this.contentTypeFromKey(resolvedToken.key);

    return {
      buffer,
      contentType,
      key: resolvedToken.key,
      cacheMaxAgeSeconds: resolvedToken.cacheMaxAgeSeconds,
    };
  }

  private validateFile(file: Express.Multer.File) {
    const extension = ALLOWED_IMAGE_TYPES.get(file.mimetype);
    if (!extension) {
      throw new UnsupportedMediaTypeException(
        'Only AVIF, GIF, JPEG, PNG, and WebP images are allowed.',
      );
    }

    if (!file.size || file.size > this.maxImageBytes) {
      throw new PayloadTooLargeException(
        `Image must be smaller than ${Math.round(this.maxImageBytes / 1024 / 1024)} MB.`,
      );
    }

    return extension;
  }

  private buildObjectKey(userId: string, extension: string) {
    const random = crypto.randomBytes(24).toString('hex');
    return `${EDITOR_IMAGE_PREFIX}/${userId}/${random}.${extension}`;
  }

  private createImageToken(key: string) {
    const payload = Buffer.from(
      JSON.stringify({
        v: TOKEN_VERSION,
        key,
        exp: Math.floor(Date.now() / 1000) + this.tokenTtlSeconds,
      }),
      'utf8',
    ).toString('base64url');
    const signature = this.sign(payload);

    return `${payload}.${signature}`;
  }

  private verifyImageToken(token: string): {
    key: string;
    cacheMaxAgeSeconds: number;
  } {
    const [payload, signature] = token.split('.');
    if (!payload || !signature) {
      throw new BadRequestException('Invalid image token.');
    }

    const expected = this.sign(payload);
    const actualBuffer = Buffer.from(signature, 'base64url');
    const expectedBuffer = Buffer.from(expected, 'base64url');

    if (
      actualBuffer.length !== expectedBuffer.length ||
      !crypto.timingSafeEqual(actualBuffer, expectedBuffer)
    ) {
      throw new BadRequestException('Invalid image token.');
    }

    let parsed: { v?: string; key?: string; exp?: number };
    try {
      parsed = JSON.parse(
        Buffer.from(payload, 'base64url').toString('utf8'),
      ) as {
        v?: string;
        key?: string;
        exp?: number;
      };
    } catch {
      throw new BadRequestException('Invalid image token.');
    }

    if (parsed.v !== TOKEN_VERSION || !this.isValidEditorImageKey(parsed.key)) {
      throw new BadRequestException('Invalid image token.');
    }

    if (typeof parsed.exp === 'number') {
      const nowSeconds = Math.floor(Date.now() / 1000);

      if (parsed.exp <= nowSeconds) {
        throw new BadRequestException('Image token has expired.');
      }

      return {
        key: parsed.key,
        cacheMaxAgeSeconds: Math.max(parsed.exp - nowSeconds, 0),
      };
    }

    // Legacy tokens created before expiry support remain valid for existing
    // documents; new uploads always receive expiring tokens.
    return {
      key: parsed.key,
      cacheMaxAgeSeconds: DEFAULT_IMAGE_TOKEN_TTL_SECONDS,
    };
  }

  private isValidEditorImageKey(key: unknown): key is string {
    return (
      typeof key === 'string' &&
      key.startsWith(`${EDITOR_IMAGE_PREFIX}/`) &&
      !key.includes('..')
    );
  }

  private sign(payload: string) {
    const secret = this.config.getOrThrow<string>('ENCRYPTION_SECRET');

    return crypto
      .createHmac('sha256', secret)
      .update(payload)
      .digest('base64url');
  }

  private contentTypeFromKey(key: string) {
    if (key.endsWith('.avif')) return 'image/avif';
    if (key.endsWith('.gif')) return 'image/gif';
    if (key.endsWith('.png')) return 'image/png';
    if (key.endsWith('.webp')) return 'image/webp';
    return 'image/jpeg';
  }
}
